### ISSUE TITLE
Couldn't find materialize function ''leanModal' 

### ISSUE THREAD

**Issue by ziracmo** [InfomediaLtd/angular2-materialize#152]
Hi everyone !

I'm actually testing my application with angular 2.1.2. And i'm trying to query the button from my html component. I have angular2-materialize 6.0.0
Or an error appear :
```
	Error: Error in ./DescriptorComponent class DescriptorComponent - inline template:119:14 caused by: Couldn't find materialize function ''leanModal' on element or the global Materialize object.
	Error: Couldn't find materialize function ''leanModal' on element or the global Materialize object
```

The html :
 ```
<button class="btn-floating white tooltipeed modal-trigger" materialize="leanModal" data-target="editTrame" [disabled]="!user.permissions[env.name].write"
                    [materializeParams]="[{dismissible: false}]"><i class="material-icons light-green-text">edit</i>
            </button>
```

The query from the test :

`        let buttons = fixture.debugElement.queryAll(By.css('button'));
`

I've already imports The MaterializeModule into my tests i d'ont know what to do to ovoid this error.

Thanks for your help.

**Comment by rubyboy** [comment]
@ziracmo leanModal is not supported in the latest version of MaterializeCSS. Please check out their [documentation](http://materializecss.com/modals.html).
If you need to use the older version please use a pre-6 version of angular2-materialize

**Comment by ziracmo** [comment]
Thank you !

I was just refering to the [documentation](https://www.npmjs.com/package/angular2-materialize) which tell us to init a modal using this. 

`<a materialize="leanModal" [materializeParams]="[{dismissible: false}]" class="waves-effect waves-light btn modal-trigger" href="#modal1">Modal</a>`

So we must have an older version to use modal or there is an other way to do this now ?

**Comment by rubyboy** [comment]
@ziracmo thanks for pointing out the documentation issue. I've fixed it now:
```html
<!-- Modal Trigger -->
<a class="waves-effect waves-light btn modal-trigger" (click)="openModal()">Modal</a>

<!-- Modal Structure -->
<div id="modal1" class="modal bottom-sheet" materialize="modal" [materializeParams]="[{dismissible: false}]" [materializeActions]="modalActions">
  <div class="modal-content">
    <h4>Modal Header</h4>
    <p>A bunch of text</p>
  </div>
  <div class="modal-footer">
    <a class="waves-effect waves-green btn-flat" (click)="closeModal()">Close</a>
    <a class="modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
  </div>
</div>
```
```js
 modalActions = new EventEmitter<string|MaterializeAction>();
  openModal() {
    this.modalActions.emit({action:"modal",params:['open']});
  }
  closeModal() {
    this.modalActions.emit({action:"modal",params:['close']});
  }
```

**Comment by ihabZhaika** [comment]
on npm , still the old code that gives the error

**Comment by rubyboy** [comment]
I know. It waits for a new release (docs update don't release to npm). I'll push a dummy update to fix that now :)

**Comment by ziracmo** [comment]
Sorry again...

So i'm using exactly the same code you gave me. However an error appear when i click on the button. And the modal doesn't appear.

`k.velocity is not a function`

I've tryed with multiple version of jQuery ( 2.1.1, 3.1.1, 2.2.4 ) but this error is still there. I think i'm correctly importing my scripts and style 

```json
"styles": [
        "styles.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.min.js",
        "../node_modules/materialize-css/dist/js/materialize.min.js"
      ],
```

And i'm importing materialize.css in my style.css like the documentation. I'm actually using angular-cli webpack 1.0.0-beta.19-3 if you want to know.

**Comment by rubyboy** [comment]
I saw some comments in other issues (search "velocity" or CLI version in the issues) referring to using a lower version of the CLI (15 or 17, can't remember) to solve this. This error means that either jQuery or MaterializeCSS are being imported multiple times or not in the correct order (MaterializeCSS needs jQuery). MaterializeCSS adds this function on jQuery, so if it did that on one version of jQuery and another is being user later on this error will show up.

**Comment by camberos** [comment]
Thanks for the update, it's now working except the opacity doesn't show, I copied the code exactly as shown. Do I need some extra class to trigger the opacity?

<img width="1082" alt="screen shot 2016-12-07 at 11 31 19 pm" src="https://cloud.githubusercontent.com/assets/1689444/20967827/57ea0e94-bcd5-11e6-9508-ca1b87ef8016.png">

**Comment by ashuMhatugade** [comment]
Hello Rubyboy, 

Angular materialize multiple modal doesn't work-

I am trying to open three modals ,On each modals button click . In first and second attempt I'm able to open all three modals but when I'm trying to open them third time then second modal appears behind the first modal.
 So the problem is when I'm tying to open modal multiple times it will reduces the z-index of second and third modal but the first modal z-index remains same. This problem regarding to lean modal .
 Please tell me what can do now?  please reply.
