### ISSUE TITLE
MaterializeAction not found when using webpack

### ISSUE THREAD

**Issue by Ramasubramanian** [InfomediaLtd/angular2-materialize#268]
I am using the Angular 2 Webpack starter as the base. Please find the code below:

`import {MaterializeDirective, MaterializeAction} from "angular2-materialize";`
`@Input() modalActions: EventEmitter<string|MaterializeAction>;`

TS compiler complains "TS2304: Cannot find name 'MaterializeAction'." during build process. 

Reason might be MaterializeAction is defined as an interface and TS transpiles this to nothing while MaterializeDirective is a class that gets exported properly in the dist folder of angular-materialize /node_modules/angular2-materialize/dist/materialize-directive.d.ts ? 

Not sure how to fix this, should MaterializeAction be a class instead of an interface? Or is there a better solution? 

For now I am defining my own interface MaterializeAction similar to the one in your sources and using the same.

**Comment by rubyboy** [comment]
@Ramasubramanian not sure what you mean by "TS transpiles this to nothing". It should have a proper definition just like a class. Here's how the d.ts looks like:
![image](https://cloud.githubusercontent.com/assets/1908166/26031837/5c89fd34-388a-11e7-8b71-32ff77bad406.png)

Could you look at the d.ts and confirm it has the proper definition? If not, maybe try reinstalling the latest version of angular2-materialize. If that doesn't work, please share with us a repo that reproduces this problem and we could try taking a look. Thanks.

**Comment by jano42** [comment]
I've the same issue.

I forked the [Angular2-Webpack-Starter by InfomediaLts](https://github.com/InfomediaLtd/angular2-webpack-starter) to highlight this issue (and another one).

https://github.com/jano42/angular2-webpack-starter

See detail.component.ts for code:
https://github.com/jano42/angular2-webpack-starter/blob/master/src/app/%2Bdetail/detail.component.ts#L48

**Comment by rubyboy** [comment]
We may have a solution. Discussing it here: https://github.com/InfomediaLtd/angular2-materialize/issues/270

**Comment by rubyboy** [comment]
This should be fixed now with the new Webpack setup instructions.
Please follow the instructions here: https://github.com/InfomediaLtd/angular2-materialize/issues/270#issuecomment-301716772
I've also updated the fork: https://github.com/InfomediaLtd/angular2-webpack-starter
Thanks.

**Comment by Ramasubramanian** [comment]
Sorry I couldn't respond on time, Thanks to @jano42 for the fork. 

@rubyboy  by nothing i meant the transpiled materialize-directive.js which does not contain any declaration for MaterializeAction since it is an interface and TS is trying to refer this generated file instead. 

For me the solution is not working, still getting the same error. 

@jano42 What version of typescript are you using? I am using 2.2.1. I import angular2-materialize in my app.module.ts

**Comment by rubyboy** [comment]
@Ramasubramanian could you share a repo that reproduces the problem?
Any TS specifics are in the d.ts . That's where your TypeScript compiler should be taking its declarations and this specific interface.
Maybe the problem is your tsconfig that ignores the d.ts in the node_modules/angular2-materialize/dist ?

**Comment by Ramasubramanian** [comment]
@rubyboy I have forked your starter pack repo with latest updates here: https://github.com/Ramasubramanian/angular2-webpack-starter.git

Instructions:
```
npm install
npm run build:prod
```
Node version: 7.0.0
NPM version: 3.10.8

**Comment by rubyboy** [comment]
@Ramasubramanian does the dev build work for you? (npm start)
I think that maybe the reason is that I've put the config in the dev version of the webpack config. Could you try moving the following snipper from webpack.dev.js to webpack.common.js and see if that solves the problem for you?
```js
const ProvidePlugin = require('webpack/lib/ProvidePlugin');

// ...

      new ProvidePlugin({
          "window.jQuery": "jquery",
          Hammer: "hammerjs/hammer",
      }),

```

**Comment by Ramasubramanian** [comment]
I checked that already, running 
```npm run build:dev```
also give the same error error.

**Comment by rubyboy** [comment]
@Ramasubramanian you're right. The package.json was missing a reference to the types location. I've fixed that here: https://github.com/InfomediaLtd/angular2-materialize/commit/8de53ac91621f6f9e79e483d061cd03c18db9473
Are you able to reinstall angular2-materialize and confirm if this is fixed now? Thanks

**Comment by Ramasubramanian** [comment]
@rubyboy Tested and it works now! Thanks for the fix.
